# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_fit_file <- function(f1) {
    .Call('fit_decode_fit_file', PACKAGE = 'fit', f1)
}

